#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import agent.tasks
import os

request = json.load(sys.stdin)

password = request.get('password', '')

config = {
   "PASSWORD_ACCESS": f"{request.get('password_access', True)}".lower(),
   "USER_NAME": request.get('user', 'sshuser'),
   "SUDO_ACCESS": f"{request.get('sudo_access', True)}".lower()
}
agent.write_envfile('config.env', config)

if password != "":
    agent.set_env("PASSWORD", password)

if not password:
    del request['password']

# For later use and backup
with open('config.json', 'w') as cfp:
    cfp.write(json.dumps(request))
