#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# If the control reaches this step, the service can be enabled and started

touch smarthost.env

systemctl --user enable openssh.service
systemctl --user restart openssh.service
