#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

config = {'password_access': False, 'user': 'sshuser', 'password' : '', 'sudo_access': False}

try:
    # Read current configuration from config file
    with open('config.json', 'r') as cf:
        config = json.loads(cf.read())
except:
    pass
# Do not expose password 
config["password"] = ''

config["tcp_port"] = os.environ.get("TCP_PORT","")

json.dump(config, fp=sys.stdout)
